version: '3.1'  # if no version is specificed then v1 is assumed. Recommend v2 minimum

services:  # containers. same as docker run
  postgres:
    image: postgres
    environment:
    -  POSTGRES_USER=postgres
    -  POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

volumes:
  my_dbdata:

#networks: # Optional, same as docker network create



